// Auto-generated by gen_sprites.py -- do not edit by hand.
// Format: XBM (LSB-first), for U8g2 drawXBMP().
#pragma once
#include <Arduino.h>

struct Animation {
  const uint8_t* const* frames;
  uint8_t  frameCount;
  uint8_t  w, h;
  uint16_t frameMs;
  bool     loop;
};

enum Activity { REST, WALK, SLEEP };

static const uint8_t rest0_xbm[] = {0,0,0,0,0,0,0,0,224,7,16,8,40,20,136,17,152,25,8,16,8,16,208,11,32,4,0,0,0,0,0,0};
static const uint8_t* const restFrames[] = {rest0_xbm};
static const Animation ANIM_REST = {restFrames, 1, 16, 16, 150, true};

static const uint8_t sleep0_xbm[] = {7,0,4,0,2,0,1,0,23,0,0,0,32,62,0,73,128,130,128,66,128,64,128,72,128,66,128,130,0,73,0,62};
static const uint8_t* const sleepFrames[] = {sleep0_xbm};
static const Animation ANIM_SLEEP = {sleepFrames, 1, 16, 16, 150, true};

static const uint8_t walk0_xbm[] = {0,0,0,0,0,0,224,7,16,8,40,20,136,17,158,113,8,16,8,16,208,11,32,10,0,4,0,0,0,0,0,0};
static const uint8_t walk1_xbm[] = {0,0,0,0,0,0,224,7,16,8,40,20,136,17,142,121,8,16,8,16,208,11,80,4,32,0,0,0,0,0,0,0};
static const uint8_t* const walkFrames[] = {walk0_xbm,walk1_xbm};
static const Animation ANIM_WALK = {walkFrames, 2, 16, 16, 150, true};

