#!/usr/bin/env python3
"""
gen_sprites.py  -  Batch-convert a folder of monochrome PNGs into a single
                   sprites.h for U8g2 (drawXBMP / XBM = LSB-first).

Usage:
    python gen_sprites.py art/ sprites.h

Naming convention for your art files:
    <state>_<frameNumber>.png     e.g.  walk_00.png, walk_01.png, rest_00.png
Files are grouped by <state>, ordered by <frameNumber>, and emitted as:
    - one const uint8_t[] per frame
    - one const uint8_t* const <state>Frames[] table
    - one Animation ANIM_<STATE> struct

Encoding: a source pixel is treated as LIT (draws in the OLED draw color) when
it is DARK. So design your characters as BLACK shapes on a WHITE background.
Set INVERT = True if you draw the other way round.
"""
import sys, re
from pathlib import Path
from collections import defaultdict
from PIL import Image

INVERT = False        # flip if your character is light-on-dark
FRAME_MS = 150        # default per-frame duration; tweak per animation later
THRESHOLD = 128       # pixels darker than this are "lit"


def to_xbm(img):
    """Return (w, h, bytes) packed as XBM: LSB = leftmost pixel, rows byte-padded."""
    # RGBA art is usually black-on-transparent. convert("L") drops alpha and
    # leaves transparent pixels as black, so the whole sprite becomes lit.
    # Composite onto white first so transparent == background.
    if img.mode in ("RGBA", "LA") or (img.mode == "P" and "transparency" in img.info):
        rgba = img.convert("RGBA")
        bg = Image.new("RGBA", rgba.size, (255, 255, 255, 255))
        img = Image.alpha_composite(bg, rgba)
    img = img.convert("L")
    w, h = img.size
    row_bytes = (w + 7) // 8
    out = bytearray()
    for y in range(h):
        for xb in range(row_bytes):
            b = 0
            for bit in range(8):            # bit 0 is the LEFTMOST pixel (XBM/LSB-first)
                x = xb * 8 + bit
                if x < w:
                    lit = img.getpixel((x, y)) < THRESHOLD
                    if INVERT:
                        lit = not lit
                    if lit:
                        b |= (1 << bit)
            out.append(b)
    return w, h, out


def main():
    art_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "art")
    out_path = Path(sys.argv[2] if len(sys.argv) > 2 else "sprites.h")

    groups = defaultdict(list)
    for p in sorted(art_dir.glob("*.png")):
        m = re.match(r"([A-Za-z]+)_(\d+)", p.stem)
        if not m:
            print(f"  skip (bad name): {p.name}")
            continue
        groups[m.group(1)].append((int(m.group(2)), p))

    if not groups:
        sys.exit(f"No matching PNGs in {art_dir} (expected e.g. walk_00.png)")

    lines = [
        "// Auto-generated by gen_sprites.py -- do not edit by hand.",
        "// Format: XBM (LSB-first), for U8g2 drawXBMP().",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "struct Animation {",
        "  const uint8_t* const* frames;",
        "  uint8_t  frameCount;",
        "  uint8_t  w, h;",
        "  uint16_t frameMs;",
        "  bool     loop;",
        "};",
        "",
        # Keep Activity in this header so Arduino's auto-prototypes see it.
        "enum Activity { REST, WALK, SLEEP };",
        "",
    ]

    for state, items in groups.items():
        items.sort()                       # order by frame number
        names = []
        w = h = 0
        for idx, (_, path) in enumerate(items):
            w, h, data = to_xbm(Image.open(path))
            name = f"{state}{idx}_xbm"
            names.append(name)
            body = ",".join(str(b) for b in data)
            lines.append(f"static const uint8_t {name}[] = {{{body}}};")
        lines.append(
            f"static const uint8_t* const {state}Frames[] = {{{','.join(names)}}};"
        )
        lines.append(
            f"static const Animation ANIM_{state.upper()} = "
            f"{{{state}Frames, {len(items)}, {w}, {h}, {FRAME_MS}, true}};"
        )
        lines.append("")
        print(f"  {state}: {len(items)} frame(s), {w}x{h}, {len(data)} bytes/frame")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
