// tamagotchi_anim.ino
// Frame-based sprite animation on an SH1106 OLED with U8g2 (Raspberry Pi Pico).
//
// Pipeline: accelerometer -> classifier -> pick Animation -> AnimPlayer ticks
// frames on a timer -> drawXBMP into the full buffer -> sendBuffer.
//
// sprites.h is auto-generated by gen_sprites.py from your PNG art folder.

#include <U8g2lib.h>
#include <SPI.h>
#include "sprites.h"

// Integer scale for on-screen sprite size (1 = native, 2 = double, etc.).
static const uint8_t SPRITE_SCALE = 3;

// ---------------------------------------------------------------------------
// Display. _F_ = FULL buffer mode -- required for clean animation (one
// clearBuffer/draw/sendBuffer per frame). ADJUST PINS to match your wiring;
// these are GP numbers on the Pico. This is the 4-wire software-SPI form; if
// you wired to the hardware SPI pins you can switch to the _HW_SPI constructor.
U8G2_SH1106_128X64_NONAME_F_4W_SW_SPI u8g2(
    U8G2_R0,
    /* clock = */ 2,     // SCK  / D0
    /* data  = */ 3,     // MOSI / D1
    /* cs    = */ 6,
    /* dc    = */ 5,
    /* reset = */ 4);

// Draw an XBM bitmap scaled by SPRITE_SCALE (nearest-neighbour).
static void drawXBMPScaled(u8g2_uint_t x, u8g2_uint_t y,
                           uint8_t w, uint8_t h, const uint8_t* bits) {
  if (SPRITE_SCALE <= 1) {
    u8g2.drawXBMP(x, y, w, h, bits);
    return;
  }
  const uint8_t bytesPerRow = (w + 7) / 8;
  for (uint8_t row = 0; row < h; row++) {
    for (uint8_t col = 0; col < w; col++) {
      const uint8_t b = bits[row * bytesPerRow + (col >> 3)];
      if (b & (1 << (col & 7))) {
        u8g2.drawBox(x + col * SPRITE_SCALE, y + row * SPRITE_SCALE,
                     SPRITE_SCALE, SPRITE_SCALE);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Animation player. Holds which animation is active, which frame, and when it
// last advanced. Ticked once per loop; it only redraws-forward on its own clock
// so frame rate is independent of loop speed.
struct AnimPlayer {
  const Animation* anim = nullptr;
  uint8_t  frame = 0;
  uint32_t lastTick = 0;

  // Switch animations. The (a == anim) guard is essential: without it, calling
  // play() every loop resets frame to 0 every loop and the animation freezes.
  void play(const Animation* a, uint32_t now) {
    if (a == anim) return;
    anim = a;
    frame = 0;
    lastTick = now;
  }

  void update(uint32_t now) {
    if (!anim || now - lastTick < anim->frameMs) return;
    lastTick = now;
    if (++frame >= anim->frameCount)
      frame = anim->loop ? 0 : anim->frameCount - 1;
  }

  void draw(u8g2_uint_t x, u8g2_uint_t y) const {
    if (anim)
      drawXBMPScaled(x, y, anim->w, anim->h, anim->frames[frame]);
  }
};

AnimPlayer player;

// ---------------------------------------------------------------------------
// Classifier hook. Replace classifyActivity() with your real accelerometer
// logic (RMS / thresholds over a window of samples). The demo version just
// cycles states every 3 s so you can see all three animations immediately.
Activity classifyActivity(uint32_t now) {
  return (Activity)((now / 3000) % 3);          // TODO: real classifier
}

const Animation* animForActivity(Activity a) {
  switch (a) {
    case WALK:  return &ANIM_WALK;
    case SLEEP: return &ANIM_SLEEP;
    case REST:
    default:    return &ANIM_REST;
  }
}

// ---------------------------------------------------------------------------
void setup() {
  u8g2.begin();
  u8g2.setDrawColor(1);            // lit pixels = "on"; drawXBMP is transparent
}

void loop() {
  uint32_t now = millis();

  player.play(animForActivity(classifyActivity(now)), now);
  player.update(now);

  u8g2.clearBuffer();
  // centre the scaled sprite on a 128x64 panel
  const u8g2_uint_t sw = ANIM_REST.w * SPRITE_SCALE;
  const u8g2_uint_t sh = ANIM_REST.h * SPRITE_SCALE;
  player.draw((128 - sw) / 2, (64 - sh) / 2);
  u8g2.sendBuffer();

  // no delay() needed -- timing lives in AnimPlayer::update()
}
